// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: proto/collatz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollatzRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IndexFrom int64 `protobuf:"varint,1,opt,name=index_from,json=indexFrom,proto3" json:"index_from,omitempty"`
	IndexTo   int64 `protobuf:"varint,2,opt,name=index_to,json=indexTo,proto3" json:"index_to,omitempty"`
}

func (x *CollatzRequest) Reset() {
	*x = CollatzRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collatz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollatzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollatzRequest) ProtoMessage() {}

func (x *CollatzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collatz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollatzRequest.ProtoReflect.Descriptor instead.
func (*CollatzRequest) Descriptor() ([]byte, []int) {
	return file_proto_collatz_proto_rawDescGZIP(), []int{0}
}

func (x *CollatzRequest) GetIndexFrom() int64 {
	if x != nil {
		return x.IndexFrom
	}
	return 0
}

func (x *CollatzRequest) GetIndexTo() int64 {
	if x != nil {
		return x.IndexTo
	}
	return 0
}

type CollatzResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxLength int64 `protobuf:"varint,1,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	Index     int64 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *CollatzResponse) Reset() {
	*x = CollatzResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_collatz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollatzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollatzResponse) ProtoMessage() {}

func (x *CollatzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collatz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollatzResponse.ProtoReflect.Descriptor instead.
func (*CollatzResponse) Descriptor() ([]byte, []int) {
	return file_proto_collatz_proto_rawDescGZIP(), []int{1}
}

func (x *CollatzResponse) GetMaxLength() int64 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

func (x *CollatzResponse) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_proto_collatz_proto protoreflect.FileDescriptor

var file_proto_collatz_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x22, 0x4a,
	0x0a, 0x0e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x46, 0x72, 0x6f, 0x6d, 0x12,
	0x19, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x6f, 0x22, 0x46, 0x0a, 0x0f, 0x43, 0x6f,
	0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x32, 0x50, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x42, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x63, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x12,
	0x17, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74,
	0x7a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x61,
	0x74, 0x7a, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x57, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x65, 0x62, 0x61, 0x67, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74,
	0x7a, 0x42, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x62,
	0x61, 0x67, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x7a, 0x2f, 0x67, 0x6f, 0x2f,
	0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_collatz_proto_rawDescOnce sync.Once
	file_proto_collatz_proto_rawDescData = file_proto_collatz_proto_rawDesc
)

func file_proto_collatz_proto_rawDescGZIP() []byte {
	file_proto_collatz_proto_rawDescOnce.Do(func() {
		file_proto_collatz_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_collatz_proto_rawDescData)
	})
	return file_proto_collatz_proto_rawDescData
}

var file_proto_collatz_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_collatz_proto_goTypes = []interface{}{
	(*CollatzRequest)(nil),  // 0: collatz.CollatzRequest
	(*CollatzResponse)(nil), // 1: collatz.CollatzResponse
}
var file_proto_collatz_proto_depIdxs = []int32{
	0, // 0: collatz.Calculator.calcCollatz:input_type -> collatz.CollatzRequest
	1, // 1: collatz.Calculator.calcCollatz:output_type -> collatz.CollatzResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_collatz_proto_init() }
func file_proto_collatz_proto_init() {
	if File_proto_collatz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_collatz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollatzRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_collatz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollatzResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_collatz_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collatz_proto_goTypes,
		DependencyIndexes: file_proto_collatz_proto_depIdxs,
		MessageInfos:      file_proto_collatz_proto_msgTypes,
	}.Build()
	File_proto_collatz_proto = out.File
	file_proto_collatz_proto_rawDesc = nil
	file_proto_collatz_proto_goTypes = nil
	file_proto_collatz_proto_depIdxs = nil
}
